# Build Reel Rivals release artifacts into dist/
# Usage: powershell -File build.ps1 [-Version 1.0.0]
#
# Per Minecraft line, from its own source tree:
#   datapack/      -> +mc1.21.1.zip   (stable line)  + a NeoForge datapack-in-jar
#   datapack-26x/  -> +mc26.2.zip     (built only if the folder exists)
#
# The .zip is the universal artifact: drop it in world/datapacks on ANY loader
# (vanilla, Fabric, Quilt, NeoForge, Paper). The NeoForge .jar is the same content
# wrapped as a code-free `lowcodefml` mod, so it installs like a mod, applies to
# every world without per-world setup, and — the real win — loads AFTER vanilla
# automatically, so the fishing-loot override can't lose the pack-order race that
# the zip's install steps have to warn players about.
param([string]$Version = "1.0.0")
$ErrorActionPreference = "Stop"
$proj = Split-Path $PSScriptRoot -Parent
$dist = Join-Path $proj "dist"
New-Item -ItemType Directory -Force $dist | Out-Null

Add-Type -AssemblyName System.IO.Compression | Out-Null
Add-Type -AssemblyName System.IO.Compression.FileSystem | Out-Null

# Write every file under $srcDir into $outPath at the archive root, using FORWARD-SLASH
# entry names. (PS 5.1 Compress-Archive writes BACKSLASH entries, which Minecraft's zip
# reader treats as literal filename chars -> the pack enables but loads empty. Same trap
# would silently empty the jar.) $extra is a hashtable of entryPath -> string content for
# files that don't exist on disk (the jar's mods.toml).
function Write-PackArchive {
  param([string]$SrcDir, [string]$OutPath, [hashtable]$Extra = @{})
  if (Test-Path $OutPath) { Remove-Item $OutPath -Force -Confirm:$false }
  $fsOut = [System.IO.File]::Create($OutPath)
  $za = New-Object System.IO.Compression.ZipArchive($fsOut, [System.IO.Compression.ZipArchiveMode]::Create)
  try {
    Get-ChildItem $SrcDir -Recurse -File | ForEach-Object {
      $rel = $_.FullName.Substring($SrcDir.Length + 1).Replace("\", "/")
      $entry = $za.CreateEntry($rel)
      $es = $entry.Open(); $inS = [System.IO.File]::OpenRead($_.FullName)
      $inS.CopyTo($es); $inS.Dispose(); $es.Dispose()
    }
    foreach ($k in $Extra.Keys) {
      $entry = $za.CreateEntry($k)
      $es = $entry.Open()
      $bytes = [System.Text.Encoding]::UTF8.GetBytes($Extra[$k])
      $es.Write($bytes, 0, $bytes.Length); $es.Dispose()
    }
  } finally {
    $za.Dispose(); $fsOut.Dispose()
  }
  return [math]::Round((Get-Item $OutPath).Length / 1KB, 0)
}

# The datapack-in-jar's mod metadata. Generated here so `version` tracks -Version and can
# never drift. modLoader=lowcodefml == a data/resource-only mod with no Java entrypoint.
# License is All Rights Reserved to match the store-listing/jar-metadata side of the split
# licensing policy (the GitHub source is MIT).
function Get-NeoForgeModsToml {
  param([string]$Version)
  @"
# Generated by tools/build.ps1 - do not edit by hand; edit the generator.
modLoader = "lowcodefml"
loaderVersion = "[4,)"
license = "All Rights Reserved"
issueTrackerURL = "https://modrinth.com/datapack/reel-rivals"

[[mods]]
modId = "reelrivals"
version = "$Version"
displayName = "Reel Rivals"
authors = "SapperSquad"
description = '''
Competitive fishing for vanilla Minecraft: every catch is weighed, rare species spawn by
biome/weather/time, server records are tracked, and any player can host a buy-in tournament.
This is a datapack shipped as a code-free mod so it installs like a mod and always loads
after vanilla - no pack-order fiddling. The plain .zip works on any loader too.
'''

[[dependencies.reelrivals]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.reelrivals]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.22)"
    ordering = "NONE"
    side = "BOTH"
"@
}

# `mc` is the filename suffix. The 26x tree is NOT 26.2-only any more: its pack.mcmeta declares
# min_format 88 / max_format 107, a range verified live on 1.21.10 (88), 1.21.11 (94) and
# 26.1.2 (101) as well as its native 26.2 (107). One artifact, many game-version tags.
$lines = @(
  @{ src = (Join-Path $proj "datapack");     mc = "1.21.1";       neoforgeJar = $true },
  @{ src = (Join-Path $proj "datapack-26x"); mc = "1.21.10-26.2"; neoforgeJar = $false }
)
foreach ($l in $lines) {
  if (-not (Test-Path (Join-Path $l.src "pack.mcmeta"))) { continue }

  # Universal datapack zip (pack.mcmeta at zip root).
  $zip = Join-Path $dist ("ReelRivals-" + $Version + "+mc" + $l.mc + ".zip")
  $kb = Write-PackArchive -SrcDir $l.src -OutPath $zip
  "built: $zip ($kb KB)"

  # NeoForge datapack-in-jar: same content + META-INF/neoforge.mods.toml at the jar root.
  if ($l.neoforgeJar) {
    $jar = Join-Path $dist ("ReelRivals-" + $Version + "+mc" + $l.mc + "-neoforge.jar")
    $extra = @{ "META-INF/neoforge.mods.toml" = (Get-NeoForgeModsToml -Version $Version) }
    $kb = Write-PackArchive -SrcDir $l.src -OutPath $jar -Extra $extra
    "built: $jar ($kb KB)  [NeoForge datapack-in-jar]"
  }
}
"Upload the .zip under loader 'datapack' (any loader); upload the .jar under loader 'neoforge'."
